name: Manual Maven Steps for CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write
  actions: read
  security-events: write

jobs:
  manual:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          jf --version
          jf rt ping

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build package
        run: mvn package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/target/surefire-reports/TEST-*.xml

      - name: Upload packaged jar files
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-${{ matrix.java }}
          path: '**/target/*.jar'
          
